### PR TITLE
Add align-self to cell

### PR DESCRIPTION
**Pull request by ariona**
I think the align-self property can be helpfull too for cell.

### CODE REVIEW

**Comment by 1000ch** [comment]
What does anyone think about this?

**Comment by lclghst** [comment]
Personally I'd leave it out.

Let grd stay small and keep doing grids only :grin:

**Comment by davidpelayo** [comment]
I also think we should leave it out.

The responsibility is just to create grids :ok_hand:

**Comment by 1000ch** [comment]
OK, I don't add `align-self` modifiers for now.
If you demand highly again, let's consider again.

**Comment by ariona** [comment]
Ah,, no problem then :smile:

**Comment by omarseda** [comment]
whoa ariona... so this is your project .. i cliked to watch this repo yesterday..

**Comment by ariona** [comment]
@omarseda bukan masbro :smile:

**Comment by omarseda** [comment]
woh ngepull ya

**Pull request closed without merging**
